export const WORDS = [
  "AGENT",
  "WORLD",
  "ABOUT",
  "HEART",
  "WATER",
  "SIXTY",
  "BOARD",
  "MONTH",
  "MUSIC",
  "PARTY",
  "PIANO",
  "MOUTH",
  "WOMAN",
  "SUGAR",
  "AMBER",
  "DREAM",
  "LAUGH",
  "TIGER",
  "EARTH",
  "MONEY",
  "WORDS",
  "SMILE",
  "LEMON",
  "SOUTH",
  "AFTER",
  "STONE",
  "THING",
  "LIGHT",
  "STORY",
  "POWER",
  "TODAY",
  "RANGE",
  "PEARL",
  "VENOM",
  "PROXY",
  "ROUND",
  "HOVER",
  "CANDY",
  "ABOVE",
  "PHONE",
  "OTHER",
  "SMART",
  "BLACK",
  "MAGIC",
  "FRUIT",
  "RADIO",
  "ROYAL",
  "HONEY",
  "FLAKE",
  "SOUND",
];

export const KEYBOARD_KEYS = [
  { key: "Q", row: 1 },
  { key: "W", row: 1 },
  { key: "E", row: 1 },
  { key: "R", row: 1 },
  { key: "T", row: 1 },
  { key: "Y", row: 1 },
  { key: "U", row: 1 },
  { key: "I", row: 1 },
  { key: "O", row: 1 },
  { key: "P", row: 1 },
  { key: "A", row: 2 },
  { key: "S", row: 2 },
  { key: "D", row: 2 },
  { key: "F", row: 2 },
  { key: "G", row: 2 },
  { key: "H", row: 2 },
  { key: "J", row: 2 },
  { key: "K", row: 2 },
  { key: "L", row: 2 },
  { key: "ENTER", row: 3 },
  { key: "Z", row: 3 },
  { key: "X", row: 3 },
  { key: "C", row: 3 },
  { key: "V", row: 3 },
  { key: "B", row: 3 },
  { key: "N", row: 3 },
  { key: "M", row: 3 },
  { key: "DEL", row: 3 },
];
